developer-test-master/OrangeBricks.Web/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OrangeBricks.Web.Models
{
    public class Booking
    {
        [Key]
        public int BookingId { get; set; }
        public DateTime ViewDate { get; set; }

        //public int Property_Id {get;set;}
        public BookingStatus BookingStatus { get; set; }

        public string Buyer_Id { get; set;}


    }
}

developer-test-master/OrangeBricks.Web/Models/Property.cs
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OrangeBricks.Web.Models
{
    public class Property
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string PropertyType { get; set; }

        [Required]
        public string StreetName { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public int NumberOfBedrooms { get; set; }

        [Required]
        public string SellerUserId { get; set; }

        public bool IsListedForSale { get; set; }

        public ICollection<Offer> Offers { get; set; }

        public ICollection<Booking> Bookings { get; set; }


    }
}

developer-test-master/OrangeBricks.Web/Controllers/Offers/OffersController.cs
using System.Web.Mvc;
using OrangeBricks.Web.Attributes;
using OrangeBricks.Web.Controllers.Offers.Builders;
using OrangeBricks.Web.Controllers.Offers.Commands;
using OrangeBricks.Web.Models;

namespace OrangeBricks.Web.Controllers.Offers
{
    [OrangeBricksAuthorize(Roles = "Seller")]
    public class OffersController : Controller
    {
        private readonly IOrangeBricksContext _context;

        public OffersController(IOrangeBricksContext context)
        {
            _context = context;
        }

        public ActionResult OnProperty(int id)
        {
            var builder = new OffersOnPropertyViewModelBuilder(_context);
            var viewModel = builder.Build(id);

            return View(viewModel);
        }

        [HttpPost]        
        public ActionResult Accept(AcceptOfferCommand command)
        {
            var handler = new AcceptOfferCommandHandler(_context);

            handler.Handle(command);

            return RedirectToAction("OnProperty", new { id = command.PropertyId });
        }

        [HttpPost]
        public ActionResult Reject(RejectOfferCommand command)
        {
            var handler = new RejectOfferCommandHandler(_context);

            handler.Handle(command);

            return RedirectToAction("OnProperty", new { id = command.PropertyId });
        }
    }
}

developer-test-master/OrangeBricks.Web/Controllers/Property/PropertyController.cs
using System.Collections;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using OrangeBricks.Web.Attributes;
using OrangeBricks.Web.Controllers.Property.Builders;
using OrangeBricks.Web.Controllers.Property.Commands;
using OrangeBricks.Web.Controllers.Property.ViewModels;
using OrangeBricks.Web.Models;

namespace OrangeBricks.Web.Controllers.Property
{
    public class PropertyController : Controller
    {
        private readonly IOrangeBricksContext _context;

        public PropertyController(IOrangeBricksContext context)
        {
            _context = context;
        }

        [Authorize]
        public ActionResult Index(PropertiesQuery query)
        {
            var builder = new PropertiesViewModelBuilder(_context);
            var viewModel = builder.Build(query);
            return View(viewModel);
        }

        [OrangeBricksAuthorize(Roles = "Seller")]
        public ActionResult Create()
        {
            var viewModel = new CreatePropertyViewModel();

            viewModel.PossiblePropertyTypes = new string[] { "House", "Flat", "Bungalow" }
                .Select(x => new SelectListItem { Value = x, Text = x })
                .AsEnumerable();

            return View(viewModel);
        }

        [OrangeBricksAuthorize(Roles = "Seller")]
        [HttpPost]
        public ActionResult Create(CreatePropertyCommand command)
        {
            var handler = new CreatePropertyCommandHandler(_context);

            command.SellerUserId = User.Identity.GetUserId();

            handler.Handle(command);

            return RedirectToAction("MyProperties");
        }

        [OrangeBricksAuthorize(Roles = "Seller")]
        public ActionResult MyProperties()
        {
            var builder = new MyPropertiesViewModelBuilder(_context);
            var viewModel = builder.Build(User.Identity.GetUserId());

            return View(viewModel);
        }

        [HttpPost]
        [OrangeBricksAuthorize(Roles = "Seller")]
        public ActionResult ListForSale(ListPropertyCommand command)
        {
            var handler = new ListPropertyCommandHandler(_context);

            handler.Handle(command);

            return RedirectToAction("MyProperties");
        }

        [OrangeBricksAuthorize(Roles = "Buyer")]
        public ActionResult MakeOffer(int id)
        {
            var builder = new MakeOfferViewModelBuilder(_context);
            var viewModel = builder.Build(id);
            return View(viewModel);
        }

        [HttpPost]
        [OrangeBricksAuthorize(Roles = "Buyer")]
        public ActionResult MakeOffer(MakeOfferCommand command)
        {
            var handler = new MakeOfferCommandHandler(_context);

            handler.Handle(command);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Get Action to Book house viewing.
        /// </summary>
        /// <param name="command"></param>
        /// <returns></returns>
        [HttpGet]
        [OrangeBricksAuthorize(Roles = "Buyer")]
        public ActionResult BookingView(int propertyId)
        {
            var builder = new PropertyViewModelBuilder(_context);
            var propertyModel = builder.Build(propertyId);

            return View(propertyModel);
        }

        /// <summary>
        /// Method to handle booking view.
        /// </summary>
        /// <param name="command">BookingViewCommand</param>
        /// <returns></returns>
        [HttpPost]
        [OrangeBricksAuthorize(Roles ="Buyer")]
        public ActionResult BookingView(BookingViewCommand command)
        {
            var handler = new BookingViewCommandHandler(_context);
            var result = handler.Handle(command);
            var newBooking = result.Entity as Booking;
            if (result.Status)
                TempData["BookingStatus"] = "Success";
            return RedirectToAction("Index");
        }

        [HttpGet]
        [OrangeBricksAuthorize(Roles ="Buyer")]
        public ActionResult MyBooking()
        {
            var model = new MyBookingModelBuilder(_context);
            return View(model.Build(User.Identity.GetUserId()));
        }
    }
}

developer-test-master/OrangeBricks.Web/Views/Property/BookingView.cshtml
@model OrangeBricks.Web.Controllers.Property.ViewModels.PropertyViewModel
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Booking View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script>

  $(document).ready(function() {
      $("#ViewDate").datepicker({
          dateFormat: "dd/mm/yy",
          minDate: 0
          });
  });
</script>
<h2>Booking View</h2>
<p>You can now book a view for the Property @Model.PropertyType on @Model.StreetName.</p>

@using (Html.BeginForm("BookingView", "Property", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="form-group row">
        <div class="col-md-10">
            @Html.Hidden("PropertyId", Model.Id)
            @Html.Hidden("BuyerId", User.Identity.GetUserId())
            @Html.Hidden("BookingStatus", "Requested") 
                   @Html.Label("Viewing Date", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.Editor("ViewDate", new { htmlAttributes = new { @class = "form -control" } })
                    @Html.ValidationMessage("ViewDate", "", new { @class = "text-danger" })
                </div>
    </div>   
        </div>
        <div class="form-group row">
            <div class="col-md-2"></div>
            <div class="col-md-5">
                <input type="submit" class="btn btn-primary" value="Request" />
            </div>
            <div class="col-md-5">
                <a href="@Url.Action("Index", "Property")" class="btn btn-primary">
                    Go Back
                </a>
            </div>
        </div>
}

developer-test-master/OrangeBricks.Web/Views/Property/Create.cshtml
@model OrangeBricks.Web.Controllers.Property.ViewModels.CreatePropertyViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create a property listing</h2>

@using (Html.BeginForm("Create", "Property", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.PropertyType, "I want to sell my...", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.PropertyType, Model.PossiblePropertyTypes, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.StreetName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.StreetName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NumberOfBedrooms, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.NumberOfBedrooms, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create listing" />
        </div>
    </div>
}

developer-test-master/OrangeBricks.Web/Views/Property/Index.cshtml
@model OrangeBricks.Web.Controllers.Property.ViewModels.PropertiesViewModel
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Properties For Sale";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Properties For Sale</h2>
@if (TempData["BookingStatus"] == "Success")
{
    <p class="alert alert-success">Your Booking view request has been sent to House owner and will be confirmed by house owner.</p>
}
@using (Html.BeginForm("Index", "Property", FormMethod.Get, new { @class = "form-horizontal" }))
{
    <div class="form-group form-group-lg">
        @Html.LabelFor(x => x.Search, "Search:", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-8">
            @Html.TextBoxFor(m => m.Search, new { @class = "form-control", @placeholder = "Search by street or description..." })
        </div>
    <div class="col-sm-2">
        <button type="submit" class="btn btn-default">Search</button>
    </div>
    </div>
    
}

<p>@Model.Properties.Count properties matching your criteria...</p>

@foreach (var property in Model.Properties)
{
    <hr />
    <h3>@property.StreetName</h3>
    <p>@property.NumberOfBedrooms bedroom @property.PropertyType</p>
    <p>@property.Description</p>
    if (property.Offers != null)
    {
        foreach (var offer in property.Offers)
        {
            if (offer.Status == "Accepted" && offer.OfferedBy == User.Identity.GetUserId())
            {
                <div class="row"><div class="col-md-5 alert-success">your offer Amount £@offer.Amount has been accepted.</div></div>
            }
            if (offer.Status == "Rejected" && offer.OfferedBy == User.Identity.GetUserId())
            {
                <div class="row"><div class="col-md-5 alert-danger">your offer Amount £@offer.Amount has been rejected.</div></div>
            }
        }
    }
   
    <a href="@Url.Action("BookingView", "Property", new {propertyId = property.Id})" class="btn btn-primary">
        Book Viewing
    </a>
    <a href="@Url.Action("MakeOffer", "Property", new {id = property.Id})" class="btn btn-primary">
        Make Offer
    </a>
}

developer-test-master/OrangeBricks.Web/Views/Property/MakeOffer.cshtml
@using Microsoft.AspNet.Identity
@model OrangeBricks.Web.Controllers.Property.ViewModels.MakeOfferViewModel

@{
    ViewBag.Title = "Make Offer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Make Offer</h2>

<p>How much would you like to offer for the @Model.PropertyType on @Model.StreetName?</p>

@using (Html.BeginForm("MakeOffer", "Property", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Offer, "Offer in GBP", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.Hidden("PropertyId", Model.PropertyId)
            @Html.Hidden("OfferedBy", User.Identity.GetUserId())
            @Html.TextBoxFor(m => m.Offer, new {@class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Make Offer" />
        </div>
    </div>
}

developer-test-master/OrangeBricks.Web/Views/Property/MyBooking.cshtml
@model IEnumerable<OrangeBricks.Web.Controllers.Property.ViewModels.BookingListViewModel>
@{
    ViewBag.Title = "My Booking";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>My Properties</h2>
<p>Here is a list of your Booking:</p>
@foreach (var booking in Model)
{
    if (booking.BookingStatus == 0)
    {
        <div class="row">
            <div class="col-md-10">Booking view for date @booking.ViewDate is in pending status. </div>
        </div>
    }
}

developer-test-master/OrangeBricks.Web/Views/Property/MyProperties.cshtml
@model OrangeBricks.Web.Controllers.Property.ViewModels.MyPropertiesViewModel

@{
    ViewBag.Title = "My Properties";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>My Properties</h2>

<p>Here is a list of your properties:</p>

@foreach (var property in Model.Properties)
{
    <hr />
    <h3>@property.StreetName</h3>
    <p>@property.NumberOfBedrooms bedroom @property.PropertyType</p>
    <p>@property.Description</p>

    <a href="@Url.Action("OnProperty", "Offers", new {id = property.Id})">View offers that have been made on this property...</a>
  
        
    if (!property.IsListedForSale)
    {
        using (Html.BeginForm("ListForSale", "Property"))
        {
            @Html.Hidden("PropertyId", property.Id)
            <input class="btn btn-primary" type="submit" value="List Property For Sale" />
        }
    }

}